POST http://localhost:8080/content
accept: application/json
Content-Type: application/json

{
  "fragmentType": "SECTION",
  "name": "BodyCopy",
  "body": {
    "content": "<p>There's a lot of stuff to say today.</p>",
    "contentType": "html"
  },
  "extendedAttributes": {},
  "publishedStatus": "SCHEDULED",
  "publishStartDateTime": "2025-03-16 13:30:00",
  "publishEndDateTime": "2025-04-16 13:30:00"
}

###
