// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"time"

	"github.com/google/uuid"
	types "github.com/nobleach/cobaltcms/internal/types"
)

type Content struct {
	ID                 uuid.UUID
	FragmentType       string
	Name               string
	Body               types.JSONB
	ExtendedAttributes types.JSONB
	PublishedStatus    string
	PublishStart       *time.Time
	PublishEnd         *time.Time
	CreatedTs          *time.Time
	UpdatedTs          *time.Time
}

type ContentsContent struct {
	ID            uuid.UUID
	PageContentID uuid.UUID
	ContentID     uuid.UUID
	CreatedTs     *time.Time
	UpdatedTs     *time.Time
}

type FragmentType struct {
	ID        uuid.UUID
	TypeName  string
	CreatedTs *time.Time
	UpdatedTs *time.Time
}

type PublishedStatus struct {
	ID        uuid.UUID
	Status    string
	CreatedTs *time.Time
	UpdatedTs *time.Time
}
