// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	types "github.com/nobleach/cobaltcms/internal/types"
)

type Content struct {
	ID                 uuid.UUID
	ContentType        string
	Name               string
	Body               types.JSONB
	ExtendedAttributes types.JSONB
	PublishedStatus    string
	PublishStart       pgtype.Timestamptz
	PublishEnd         pgtype.Timestamptz
	CreatedTs          pgtype.Timestamptz
	UpdatedTs          pgtype.Timestamptz
}

type ContentType struct {
	ID        uuid.UUID
	TypeName  string
	CreatedTs pgtype.Timestamptz
	UpdatedTs pgtype.Timestamptz
}

type PublishedStatus struct {
	ID        uuid.UUID
	Status    string
	CreatedTs pgtype.Timestamptz
	UpdatedTs pgtype.Timestamptz
}
