// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const listAllPublishedStatuses = `-- name: ListAllPublishedStatuses :many
SELECT id, status
FROM published_statuses
`

type ListAllPublishedStatusesRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) ListAllPublishedStatuses(ctx context.Context) ([]ListAllPublishedStatusesRow, error) {
	rows, err := q.db.Query(ctx, listAllPublishedStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPublishedStatusesRow
	for rows.Next() {
		var i ListAllPublishedStatusesRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
